server:
  port: 8095
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#Spring ??
spring:
  datasource:
    sql-script-encoding: utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver #?????
    url: jdbc:mysql://localhost:3306/GroupAirTeam?useUnicode=true&characterEncoding=utf8  #DB URL
    username: root #?? (root? ??? ??)
    password: 1234 #????


#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB

  #Thymeleaf ??
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  #jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #drop, create, update
    properties:
      hibernate:
        show_sql: true #SQL ???? ???
        format_sql: true #SQL ??

  #spring:   #oAuth2 ?? (google, kakao, naver)
  profiles:
    include: oauth2    #application-oauth2.yml

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

filePath: file:///c:/groupAir/

navar.api.client-id:  FlR_0mjyLZ4jddlkIcaD
navar.api.client-secret:  69KHv1Uryd

mail:
  # Google smtp server 사용
  host: smtp.gmail.com
  port: 587
  username: 1thsdpdms1@gmail.com #앱 비밀번호 발급받은 google 계정
  password: cbro rcet scuz futh #발급받은 앱 비밀번호
  properties:
    mail:
      smtp:
        starttls:
          enable: true
        auth: true
